mod transfer;
mod compare;
mod smart_match;
mod backup;
mod data_compare;
mod transaction;
mod incremental;
mod sql_generator;
mod table_sync;
mod maintenance;
mod kv_adapter;
mod timeseries_adapter;
mod sharding;
mod query_fusion;
mod distributed_tx;
mod multi_db_manager;
mod metadata;
mod sql_executor;
mod session;
mod slow_query;
mod newsql;
mod auto_sharding;
mod log_table;
mod cross_db_conversion;
mod data_migration;
mod smart_sharding;

pub use transfer::{DataTransfer, StructureMigration};
pub use compare::{SchemaComparator, FieldMapper, SchemaComparison};
pub use smart_match::{SmartFieldMatcher, FieldMatcherConfig, MatchStrategy, MatchResult, MatchType, TargetSchemaInfo, ConversionSuggestionGenerator, ConversionSuggestion, SuggestionType, Priority, ConversionSuggestions};
pub use backup::{DatabaseBackup, BackupConfig, BackupType, BackupMetadata, BackupProgress, BackupPhase, RestoreReport, BackupVerificationReport, IncrementalBackupTracker, ChangeRecord};
pub use data_compare::{DataCompareConfig, CompareMode, CompareResult, SchemaDiff, SchemaDiffType, DataDiff, DataDiffType, RowDiff, CompareStats, DataComparer};
pub use transaction::{TransactionManager, TransactionExecutor};
pub use incremental::{IncrementalSync, IncrementalConfig, ConflictResolution, SyncResult};
pub use sql_generator::{SqlGenerator, SqlGeneratorConfig, FieldConnectionMapper, PlaceholderStyle};
pub use table_sync::{TableSync, TableSyncConfig, SyncMode, ConflictStrategy};
pub use maintenance::{DatabaseMaintainer, DatabaseBackup as DbBackup, DatabaseRestore, OptimizationResult, RepairResult, CleanupResult, DatabaseStatus, BackupResult, RestoreResult};
pub use kv_adapter::{RedisConverter, MongoDbConverter, KvConversionConfig, KvDataType, JsonMode, FieldMergeStrategy, RedisCommand, MongoOperation, KvConversionResult, BatchKvConverter};
pub use timeseries_adapter::{TimeSeriesConfig, TimeSeriesConverter, InfluxDbConverter, TimescaleDbConverter, TaodbConverter, TimeSeriesPoint, MetricValue, PartitionStrategy, TimeInterval, BatchWriteResult, WriteStatus};
pub use sharding::{ShardingConfig, ShardingStrategy, ShardingManager, ShardInfo, ShardParam, ShardMigrationPlan, ShardMigrationTask, ShardRouter, GlobalShardingManager};
pub use query_fusion::{QueryFusionEngine, FusionQuery, FusionResult, FusionStrategy, CrossShardPlan, QueryAnalysis, QueryType, ComplexityLevel, UnionStrategy, JoinStrategy, JoinType};
pub use distributed_tx::{DistributedTransaction, TxParticipant, TxStatus, ParticipantStatus, DistributedTxManager, TxCoordinator, SagaTransaction, SagaStep, CompensationStep, SagaStatus, SagaManager, XaTransaction, XaResourceManager, XaState};
pub use multi_db_manager::{MultiDatabaseConfig, DatabaseInstanceConfig, DatabaseInstance, MultiDatabaseManager, DatabaseInfo, HealthStatus, BackupInfo, BackupStatus, DatabaseRouter, RoutingRule, TableRouter, TableShardingRule, ShardingType as DbShardingType};
pub use metadata::{DatabaseMetadata, TableMetadata, FieldMetadata, ForeignKeyMetadata, ViewMetadata, FunctionMetadata, FunctionArgument, StoredProcedureMetadata, TriggerMetadata, IndexMetadata, MetadataManager};
pub use sql_executor::{SqlExecutor, ExecutionResult, ExecutionMetadata, QueryBuilder, SqlType};
pub use session::{Session, SessionManager, DatabaseSession, ViewManager, FunctionManager, IndexManager, ViewOperation};
pub use slow_query::{SlowQueryConfig, SlowQueryLog, QueryProfile, IndexUsageInfo, QueryOptimizationSuggestion, IssueType, Severity, SlowQueryDetector, QueryMetrics};
pub use newsql::{NewSqlAnalyzer, NewSqlCapabilities, PerformanceMetrics, DistributionInfo, NodeHealth, NodeStatus, NodeRole, ShardAnalysis, ShardingType, DataSkewReport, ConflictAnalysis, HotRecord, NewSqlOptimizationResult, QueryRouter, RoutingRule as SqlRoutingRule, ConsistencyCheck, ConsistencyStatus, RepairReport, NewSqlShardInfo, SplitPoint, NewSqlAnalyzerBuilder};
pub use auto_sharding::{TableConfig, ShardStrategy, ShardInfo as AutoShardInfo, SpanningQueryResult, CompressionConfig, AutoShardingManager, StorageBackend, CompressionHandler, SmartAutoOptimizer, OptimizationRule, OptimizationReport, ShardSummary, TableHealthReport, HealthSeverity, UnifiedQuery, CrudOperation, UnifiedCrudExecutor, ShardMigrationPlanner, MigrationStep, ShardRebalancer};
pub use log_table::{LogTableConfig, PartitionType, LogPartition, LogQuery, LogQueryResult, LogStats, LogTableManager, LogAggregator, TimeWindowAggregation, LogEntry, LogAggregationResult, ErrorSpike};
pub use cross_db_conversion::{CrossDbConverter, TypeMappingTable, TypeMappingRule, FieldLinker, FieldLink, LinkKind, DdlGenerator, ValueTransformer, ValueConversion, ConversionReport, TargetDbKind, version_adjusted_type};
pub use data_migration::{DataMigrator, MigrationConfig, MigrationDirection, TableMigrationResult, FieldMigration};
pub use smart_sharding::{SmartShardTopology as ShardTopology, SmartShardNode as ShardNode, ShardStrategyKind, QueryCoordinator, WriteCoordinator, SmartSpanningQuery as SpanningQuery, ShardResult, MergeStrategy, AggregateKind, RebalancePlan, ShardMove, WriteOp as ShardWriteOp, WriteResult as ShardWriteResult, WriteReport as ShardWriteReport};
